image: quay.io/pantheon-public/build-tools-ci:5.x

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - CI_BRANCH=$BITBUCKET_BRANCH CI_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER PR_NUMBER=$BITBUCKET_PR_ID /build-tools-ci/scripts/set-environment
          - terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
          - source ~/.bashrc && ./.ci/test/static/run
          - source ~/.bashrc && ./.ci/build/php
          - source ~/.bashrc && ./.ci/deploy/pantheon/dev-multidev
          - source ~/.bashrc && ./.ci/test/behat/initialize
          - source ~/.bashrc && ./.ci/test/behat/run
          - source ~/.bashrc && ./.ci/test/behat/cleanup
          - source ~/.bashrc && ./.ci/test/visual-regression/run
